services:
  # stockmarketassistant.frontend:
  #   image: ${DOCKER_REGISTRY-}stockmarketassistantfrontend
  #   build:
  #     context: src/frontend
  #     dockerfile: Dockerfile

  webui:
    build:
      context: src/frontend
      dockerfile: Dockerfile
    ports:
      - "5273:5273"
    environment:
      - PORT=5273
      - VITE_AUTH_API_URL=http://authservice.webapi:8080
      - VITE_STOCKCARD_API_URL=http://stockcardservice.webapi:8080
      - VITE_PORTFOLIO_API_URL=http://portfolioservice.webapi:8080
      - VITE_ANALYTICS_API_URL=http://analyticsservice.webapi:8080
    depends_on:
      - authservice.webapi
      - stockcardservice.webapi
      - portfolioservice.webapi
      - analyticsservice.webapi
    networks:
      - aspire-net

  notificationservice:
    image: notificationservice
    build:
      context: .
      dockerfile: src/backend/services/NotificationService/Notification/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__notificationDb=Host=notification-db;Port=5432;Database=notificationDb;Username=postgres;Password=postgres
      - OpenSearchConfig__Url=admin
      - OpenSearchConfig__Password=admin
      - OpenSearchConfig__Url=http://opensearch:9200
      - FRONTEND_ORIGIN=http://localhost:5273 
      
      - Aspire__Confluent__Kafka__Producer__BootstrapServers=kafka:9092
      - Aspire__Confluent__Kafka__Producer__ClientId=my-docker-producer
      - Aspire__Confluent__Kafka__Producer__Acks=all
      - Aspire__Confluent__Kafka__Producer__EnableIdempotence=true
      - Aspire__Confluent__Kafka__Producer__MaxInFlight=5

      - Aspire__Confluent__Kafka__Consumer__BootstrapServers=kafka:9092
      - Aspire__Confluent__Kafka__Consumer__GroupId=notification
      - Aspire__Confluent__Kafka__Consumer__AutoOffsetReset=earliest
      - Aspire__Confluent__Kafka__Consumer__EnableAutoCommit=false
    ports:
      - "8080"
      # - "8081"
    depends_on:
      - notification-db
      - kafka
      - opensearch
    networks:
      - aspire-net

  portfolioservice.webapi:
    image: portfolioservicewebapi
    build:
      context: .
      dockerfile: src/backend/services/PortfolioService/PortfolioService.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__portfolio-db=Host=pg-portfolio-db;Port=5432;Database=portfolio-db;Username=postgres;Password=postgres
      - OpenSearchConfig__Url=http://opensearch:9200
      # - PortfolioService__BaseUrl=http://portfolioservice-api:8080
      - FRONTEND_ORIGIN=http://localhost:5273 
    ports:
      - "8080"
      # - "8081"
    depends_on:
      - pg-portfolio-db
      - kafka
      - cache
    networks:
      - aspire-net



  stockcardservice.webapi:
    image: stockcardservicewebapi
    build:
      context: .
      dockerfile: src/backend/services/StockCardService/StockCardService.WebApi/Dockerfile
    depends_on:
      - pg-stock-card-db
      - mongo-stock-card-db
      - cache
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__stock-card-db=Host=pg-stock-card-db;Port=5432;Database=stock-card-db;Username=postgres;Password=postgres
      - ConnectionStrings__mongo=mongodb://mongo-stock-card-db:27017/finantial-report-db
      - FRONTEND_ORIGIN=http://localhost:5273
    ports:
      - "8080"
      # - "8081"
    networks:
      - aspire-net

  authservice.webapi:
    image: authservicewebapi
    build:
      context: .
      dockerfile: src/backend/services/AuthService/src/AuthService.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=
      - ConnectionStrings__Database=Host=pg-auth-db;Port=5432;Database=Database;Username=postgres;Password=postgres
      - FRONTEND_ORIGIN=http://localhost:5273
    ports:
      - "8080"
      # - "8081"
    depends_on:
      - pg-auth-db
    networks:
      - aspire-net

  analyticsservice.webapi:
    image: analyticsservicewebapi
    build:
      context: .
      dockerfile: src/backend/services/AnalyticsService/AnalyticsService.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      # - "8081"
    networks:
      - aspire-net

  notification-db:
    image: postgres:17.5
    ports:
      - "14054:5432"
    environment:
      POSTGRES_DB: notificationDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - notification-pg-data:/var/lib/postgresql/data
    networks:
      - aspire-net
  
  pg-portfolio-db:
    image: postgres:17.5
    ports:
      - "14050:5432"
    environment:
      POSTGRES_DB: portfolio-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - portfolio-pg-data:/var/lib/postgresql/data
    networks:
      - aspire-net
  pg-stock-card-db:
    image: postgres:17.5
    ports:
      - "14052:5432"
    environment:
      POSTGRES_DB: stock-card-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - stock-card-pg-data:/var/lib/postgresql/data
    networks:
      - aspire-net

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    ports:
       - "9200:9200"
       - "9600:9600"
    environment:
       discovery.type: single-node
       plugins.security.disabled: "true"
       OPENSEARCH_INITIAL_ADMIN_PASSWORD: admin
    networks:
        - aspire-net
  
  opensearch-dashboards:
     image: opensearchproject/opensearch-dashboards:2.11.0
     ports:
       - "5601:5601"
     environment:
       OPENSEARCH_HOSTS: http://opensearch:9200
       DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
     depends_on:
       - opensearch
     networks:
        - aspire-net

  kafka:
     image: apache/kafka:3.7.0
     ports:
       - "9092:9092"
     environment:
       KAFKA_PROCESS_ROLES: broker,controller
       KAFKA_NODE_ID: 1
       KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
     networks:
        - aspire-net

  kafka-ui:
     image: provectuslabs/kafka-ui:latest
     ports:
       - "9100:8080"
     environment:
       KAFKA_CLUSTERS_0_NAME: local
       KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
     depends_on:
       - kafka
     networks:
      - aspire-net
 
  pgweb-notification:
    image: sosedoff/pgweb:latest
    ports:
      - "5000:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@notification-db:5432/notificationDb?sslmode=disable
    depends_on:
      - notification-db
    networks:
      - aspire-net
  
  pgweb-stock-card:
    image: sosedoff/pgweb:latest
    ports:
      - "5001:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@pg-stock-card-db:5432/stock-card-db?sslmode=disable
    depends_on:
      - pg-stock-card-db
    networks:
      - aspire-net
      
  pg-analytics-db:
    image: postgres:17.5
    ports:
      - "14055:5432"
    environment:
      POSTGRES_DB: analytics-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - analytics-pg-data:/var/lib/postgresql/data
    networks:
      - aspire-net
#DB
  mongo-stock-card-db:
    image: mongo:8.0.15
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: finantial-report-db
    volumes:
      - stock-card-mongo-data:/data/db
    networks:
      - aspire-net

  mongo-express:
    image: mongo-express:1.0.0
    ports:
      - "5005:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-stock-card-db
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo-stock-card-db
    networks:
      - aspire-net
  cache:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - aspire-net
  pg-auth-db:
    image: postgres:17.5
    ports:
      - "14051:5432"
    environment:
      POSTGRES_DB: Database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - auth-pg-data:/var/lib/postgresql/data
    networks:
      - aspire-net

volumes:
  portfolio-pg-data:
  auth-pg-data:
  stock-card-pg-data:
  stock-card-mongo-data:
  notification-pg-data:
  analytics-pg-data:
networks:
  aspire-net:
    driver: bridge   