services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: analytics-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2183:2181"  # Используем порт 2183 на хосте, чтобы избежать конфликтов
    networks:
      - analytics_network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: analytics-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - analytics_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: analytics-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_analytics_data:/var/lib/postgresql/data
    networks:
      - analytics_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d analytics-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  akhq:
    image: tchiotludo/akhq:latest
    container_name: analytics-akhq
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
    volumes:
      - ./akhq-application.yml:/app/application.yml
    networks:
      - analytics_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_analytics_data:

networks:
  analytics_network:
    driver: bridge






